# Generated by Django 3.2.9 on 2021-11-12 01:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_accounthistory_transaction_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accounthistory',
            name='account',
        ),
        migrations.AddField(
            model_name='account',
            name='accounthistory',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.accounthistory'),
        ),
    ]
