# Generated by Django 3.2.9 on 2021-11-12 02:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20211112_0154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='accounthistory',
        ),
        migrations.AddField(
            model_name='accounthistory',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.account'),
        ),
    ]
