# Generated by Django 3.2.9 on 2021-11-12 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20211112_0212'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounthistory',
            name='price',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
